tinkerbell/charts

- .github/CODEOWNERS
- .github/codecov.yml
- .github/mergify.yml
- .github/settings.yml
This add initial repo settings.
Fixes: #
I have:
> Initial repo settings

- tinkerbell/rufio/templates/cluster-role.yaml
The values.yaml file specifies a ClusterRole name that is used in the ClusterRoleBinding, but it is not used when naming the ClusterRole. Use `.Values.rufio.managerRoleName` when creating the ClusterRole rather than the hardcoded value `manager-role` which does not mat the values.yaml setting.
rufio-controller-manager failes to start with the following error
```
W0927 16:59:01.602603       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: failed to list *v1alpha1.Task: tasks.bmc.tinkerbell.org is forbidden: User "system:serviceaccount:default:rufio-controller-manager" cannot list resource "tasks" in API group "bmc.tinkerbell.org" at the cluster scope: RBAC: clusterrole.rbac.authorization.k8s.io "rufio-manager-role" not found
E0927 16:59:01.602623       1 …
```
> Use managerRoleName to set Rufio's ClusterRole name

- tinkerbell/boots/Chart.yaml
- tinkerbell/boots/values.yaml
- tinkerbell/rufio/templates/deployment.yaml
- tinkerbell/rufio/values.yaml
- tinkerbell/stack/values.yaml
- tinkerbell/tink/Chart.yaml
- tinkerbell/tink/crds/hardware-crd.yaml
- tinkerbell/tink/values.yaml
Clean up of service naming and labels and update all service versions to their latest tags.
Fixes: #
I have:
> Update all service to release versions:

- tinkerbell/stack/README.md
- tinkerbell/stack/templates/service.yaml
- tinkerbell/stack/values.yaml
This add documentation for the stack chart `values.yaml` file. #10 should be merged first.
Fixes: #5 
I have:
> Update stack chart doc

- .github/workflows/tags.yaml
- RELEASING.md
- contrib/tag-release.sh
This includes pushing the helm chart to ghcr.io
Fixes: #
I have:
> Add release process:

- tinkerbell/stack/Chart.yaml
The version was not updated with the last 0.1.1 release.
Fixes: #
I have:
> Update stack version

- tinkerbell/hegel/Chart.yaml
- tinkerbell/hegel/values.yaml
- tinkerbell/stack/Chart.lock
- tinkerbell/stack/Chart.yaml
- tinkerbell/stack/values.yaml
This updates the chart to use the v0.8.0 version of Hegel.
Fixes: #
I have:
> Update hegel version

- tinkerbell/stack/Chart.yaml
> Update stack chart version to 0.2.0

- tinkerbell/boots/Chart.yaml
- tinkerbell/hegel/Chart.yaml
- tinkerbell/rufio/Chart.yaml
- tinkerbell/stack/Chart.lock
- tinkerbell/stack/Chart.yaml
- tinkerbell/tink/Chart.yaml
Having updated the values yaml of all charts their individual chart versions need bumping to represent the breaking change.
> Update individual chart versions after values.yaml structure changes

- tinkerbell/stack/values.yaml
New version provides a lot of fixes. tink worker retrying, vlan support, removes ca.pem issues, proxy support, unused hegel calls, etc.
Fixes: #
I have:
> Update Hook to v0.8.0:

- tinkerbell/stack/templates/nginx.yaml
- tinkerbell/stack/values.yaml
Moving to alpine means we don't have to do any apt updates or package installs. These apt commands can cause issues and are unnecessary.
Fixes: #
I have:
> Move to alpine image for downloading Hook:

- tinkerbell/stack/templates/nginx.yaml
- tinkerbell/stack/values.yaml
Adds some flexibility.
Fixes: #
I have:
> Make the download location for Hook files configurable:

- tinkerbell/hegel/Chart.yaml
- tinkerbell/hegel/values.yaml
- tinkerbell/stack/Chart.lock
- tinkerbell/stack/Chart.yaml
- tinkerbell/stack/values.yaml
> Update Hegel v0.11.0 -> v0.11.1

- tinkerbell/rufio/Chart.yaml
- tinkerbell/rufio/values.yaml
- tinkerbell/stack/Chart.lock
- tinkerbell/stack/Chart.yaml
- tinkerbell/stack/values.yaml
This has provider specific options and fixes in bmclib.
Fixes: #
I have:
> Update Rufio to latest:

- tinkerbell/stack/Chart.yaml
- tinkerbell/stack/templates/nginx-configmap.yaml
Slow clients, which are very common for firmware iPXE, will fail with this timeout. Also, updated all DNS names to be fully qualified. Bump the stack chart version in prep for a new release.
Fixes: #
I have:
> nginx update for tftp

- tinkerbell/smee/Chart.yaml
- tinkerbell/smee/values.yaml
- tinkerbell/stack/Chart.lock
- tinkerbell/stack/Chart.yaml
- tinkerbell/stack/values.yaml
Update Smee to v0.11.0
Fixes: #
I have:
> Update Smee to v0.11.0

- tinkerbell/smee/Chart.yaml
- tinkerbell/smee/templates/deployment.yaml
- tinkerbell/smee/values.yaml
- tinkerbell/stack/Chart.lock
- tinkerbell/stack/Chart.yaml
Fix a spelling issue in the Smee chart. Bump stack chart version in preparation for the next release.
Fixes: #
I have:
> Fix spelling issue in Smee chart

- tinkerbell/smee/templates/deployment.yaml
- tinkerbell/smee/values.yaml
- added flexibility for non-standard scenarios
Signed-off-by: Ricardo Pardini <ricardo@pardini.net>
> smee: add additionalVolumes & additionalVolumeMounts

- tinkerbell/smee/Chart.yaml
- tinkerbell/smee/templates/deployment.yaml
- tinkerbell/smee/values.yaml
- tinkerbell/stack/Chart.lock
- tinkerbell/stack/Chart.yaml
Allow setting the dhcp mode for smee.
Fixes: #124 
I have:
> Add field for Smee dhcp mode:

- tinkerbell/stack/values.yaml
Update HookOS version to latest.
Fixes: #
I have:
> Update HookOS version to latest

- tinkerbell/rufio/crds/bmc.tinkerbell.org_jobs.yaml
- tinkerbell/rufio/crds/bmc.tinkerbell.org_machines.yaml
- tinkerbell/rufio/crds/bmc.tinkerbell.org_tasks.yaml
- tinkerbell/tink/crds/hardware-crd.yaml
- tinkerbell/tink/crds/template-crd.yaml
- tinkerbell/tink/crds/workflow-crd.yaml
New service releases have some changes.
Fixes: #
I have:
> Update Tink and Rufio CRDs:

- tinkerbell/tink/templates/tink-controller/role.yaml
The Role/ClusterRole resource needs to be the plural to work properly.
Fixes: #
I have:
> Fix permission issue:

- tinkerbell/rufio/crds/bmc.tinkerbell.org_machines.yaml
- tinkerbell/rufio/crds/bmc.tinkerbell.org_tasks.yaml
New CRD changes.
Fixes: #
I have:
> Update Rufio CRDs

- tinkerbell/stack/templates/nginx.yaml
- tinkerbell/stack/values.yaml
Allows customization for things like load balancer.
Fixes: #62 
I have:
> Add nginx service annotations:

- tinkerbell/rufio/Chart.yaml
- tinkerbell/rufio/values.yaml
- tinkerbell/stack/values.yaml
This has a bug fix for virtual media ejecting.
Fixes: #
I have:
> Update Rufio version:

- tinkerbell/stack/values.yaml
> Bump HookOS to latest:

- tinkerbell/smee/Chart.yaml
- tinkerbell/smee/values.yaml
- tinkerbell/stack/Chart.lock
- tinkerbell/stack/Chart.yaml
- tinkerbell/stack/values.yaml
Smee has a new implementation for ISO patching that is needed for redfish emulation with sushy-tools to work.
Fixes: #
I have:
> Bump Smee and Stack versions:

- tinkerbell/stack/Chart.lock
- tinkerbell/stack/Chart.yaml
- tinkerbell/stack/values.yaml
- tinkerbell/tink/Chart.yaml
- tinkerbell/tink/values.yaml
This version has a fix in the tink-controller for a stuck STATE_PREPARING Workflow state.
Fixes: #
I have:
> Update to latest Tink version:
