tinkerbell/charts

tinkerbell/hegel/templates/deployment.yaml
Hegel replaced the TRUSTED_PROXIES environment variable with HEGEL_TRUSTED_PROXIES. Since TRUSTED_PROXIES was removed, the helm chart no longer works. This updates it to used the correct environment variable.
Signed-off-by: Thomas Miller <git@me.tmiller.dev>
=> Rename TRUSTED_PROXIES to HEGEL_TRUSTED_PROXIES

tinkerbell/stack/values.yaml
This fixes the issue in the released chart version v0.1.0, where the `loadBalancerIP` is not being set for the stack service spec.
The released chart version v0.1.0 is broken. Stack service never gets a load balancer IP.
Fixes: #
Install the helm chart from `ghcr.io`.
```bash
helm install oci://ghcr.io/tinkerbell/charts/stack stack-release --version 0.1.0 --create-namespace --namespace tink-system --wait --set "boots.boots.trustedProxies=${trusted_proxies}" --set "hegel.hegel.trustedProxies=${trusted_proxies}"
```
Observe that the `tink-stack` service doesn't get an `External-IP`.
```bash
NAMESPACE     NAME             TYPE           CLUSTER-IP      EXTERNAL-IP  PORT(S)                                          AGE
tink-system   tink-stack       LoadBalancer   10.43.113.46    <pending> …
```
=> Fix loadBalancerIP value to match expected in service.yaml:

README.md, tinkerbell/hegel/Chart.yaml, tinkerbell/stack/Chart.lock, tinkerbell/stack/Chart.yaml
Update the Hegel chart's `appVersion` property to match the Hegel version being used. As per the Helm recommendations, this also forces a patch number increase to the Chart version.
Closes #16
=> Update Hegel appVersion

tinkerbell/boots/templates/deployment.yaml, tinkerbell/boots/values.yaml, tinkerbell/hegel/templates/deployment.yaml
There's no way to deploy Boots or Hegel such that trusted proxies aren't required so we should error out if not present.
=> Make Hegel and Boots trusted proxies required

tinkerbell/boots/Chart.yaml, tinkerbell/boots/templates/deployment.yaml, tinkerbell/boots/values.yaml, tinkerbell/stack/Chart.lock, tinkerbell/stack/Chart.yaml, tinkerbell/stack/templates/kubevip.yaml, tinkerbell/stack/values.yaml
Removing the requirement for an interface for Kubevip allows Kubevip to auto discover the interface to use. Kubevip does this by looking for the interface that holds the default route.
Updating Boots' deployment strategy fixes an issue with single node deployments being unable to upgrade Boots because of host ports being in use.
Fixes: #19 
I have:
=> Update Kubevip version and interface and Boots deployment strategy:

tinkerbell/stack/README.md
Signed-off-by: Xiaodong Ye <yeahdongcn@gmail.com>
Update description and value of `kubevip.interface` in chart README.md
In previous changes, the default value of `kubevip.interface` is removed to let Kubevip auto discover the interface. This PR updates document to align the change.
Fixes: #
I have:
=> Update description and value of kubevip.interface in chart README.md

tinkerbell/boots/templates/_ports.tpl, tinkerbell/boots/templates/deployment.yaml, tinkerbell/boots/templates/service.yaml, tinkerbell/boots/values.yaml, tinkerbell/stack/templates/nginx-configmap.yaml, tinkerbell/stack/templates/nginx.yaml, tinkerbell/stack/values.yaml
Refactor the boots chart to provide a foundation for values native mechanisms to configure Boots and other charts. This alleviates a number of issues:
- Can configure trusted proxies in Boots using `--set` and `{}` syntax. 
- No longer need to include all args/envs when wanting to override individual pieces of configuration.
=> Refactor boots chart to expose configuration in a values native way

tinkerbell/hegel/templates/deployment.yaml, tinkerbell/hegel/values.yaml
We found a pattern that works well and is proven out in Boots. This aligns trusted proxy configuration with the approach in Hegel.
Closes #29
=> Use a list for Hegel trusted proxy configuration

tinkerbell/stack/values.yaml
In most cases these will need to be the same so that files like the Hook kernel and initramfs will be served from the correct IP.
Fixes: #
I have:
=> Set stack.loadBalancerIP equal to boots.remoteIp:

tinkerbell/stack/templates/nginx.yaml, tinkerbell/stack/values.yaml
This enables running the stack in constrained
environments like with Kubernetes KinD. Only
the stack chart is modified. All service ports
listen on are their known/normal ones.
I.E. 50061, 42113, 8080, 80, 69, 67, 514
To enable this the following would be set in `stack/values.yaml`
```yaml
stack.service.enabled: false
boots.hostNetwork: false
```
Here's an example KinD config file that would work with this.
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
extraPortMappings:
- containerPort: 50061
hostPort: 50061
- containerPort: 42113
hostPort: 42113
- containerPort: 8080
hostPort: 8080
- containerPort: 80
hostPort: 80
- containerPort: 69
hostPort: 69
protocol: udp
- containerPort: 67
hostPort: 67
protocol: udp
- containerPort: 514
hostPort: 514 …
```
=> Allow for running the stack nginx on hostNetwork:

.github/workflows/ci.yaml, tinkerbell/boots/Chart.yaml, tinkerbell/boots/templates/service.yaml, tinkerbell/boots/values.yaml, tinkerbell/hegel/Chart.yaml, tinkerbell/hegel/templates/service.yaml, tinkerbell/stack/Chart.lock, tinkerbell/stack/Chart.yaml, tinkerbell/stack/README.md, tinkerbell/stack/templates/kubevip.yaml, tinkerbell/stack/templates/nginx-configmap.yaml, tinkerbell/stack/templates/nginx.yaml, tinkerbell/stack/templates/relay.yaml, tinkerbell/stack/values.yaml, tinkerbell/tink/Chart.yaml, tinkerbell/tink/templates/tink-server/service.yaml
This enables Boots to be deployed, scaled, etc in normal Kubernetes ways instead of the current limiting paradigm of using host networking. Also, host networking is only needed for DHCP broadcast requests and Boots serves many other things. TFTP, HTTP, Syslog.
While this requires an additional load balancer IP for Boots, it's the most reliable way to get unicast traffic into Boots. Once we migrate to the [Kubernetes gateway API ](https://gateway-api.sigs.k8s.io/) we can go back to a single IP for all services.
Other updates include:
- use cluster ips in all charts
- default to hostNetwork: false in Boots chart
- use RollingUpdate deployment strategy in Boots chart
- use trailing dot in all FQDN references (fixes issues found in KinD deployments)
- Move to ubuntu image for downloading Hook …
=> Add relay functionality:

tinkerbell/rufio/Chart.yaml, tinkerbell/rufio/crds/bmc.tinkerbell.org_jobs.yaml, tinkerbell/rufio/crds/bmc.tinkerbell.org_tasks.yaml, tinkerbell/rufio/values.yaml, tinkerbell/stack/Chart.lock, tinkerbell/stack/Chart.yaml
Virtual media support was added to rufio in https://github.com/tinkerbell/rufio/pull/79. This PR exposes the functionality here.
It should probably also bump the rufio version, but I think a maintainer might have to publish a new release first?
Booted a cluster with virtual media after installing tinkerbell with these charts.
I have:
=> Update CRDs so rufio can handle virtual media

tinkerbell/stack/templates/nginx.yaml
This ensures that whatever pre-built Kernel image had been baked into the NGINX Docker image is served.
Due to missing device drivers in the vanilla Hook Linux Kernel we had to build our own. To avoid having to host an additional HTTP(S) server that serves the resulting Kernel image and Ramdisk we had decided to directly bake those files into the NGINX Docker Image and overriden the `stack.image` value accordingly.
By setting `stack.hook.enabled` we can disable the init container that pulls files from a 3rd party HTTP(S) server. However this doesn't work, as an empty `/opt/hook` directory from the host is still mounted into the target Pod.
This MR changes this behavior. When `stack.hook.enabled` is set to `false` only the Kernel files already in the Hook Docker Image are served instead. …
=> Disable mounting /opt/hook from host if stack.hook.enabled is set to false

tinkerbell/boots/templates/service.yaml, tinkerbell/stack/templates/nginx.yaml
only set the loadBalancerClass property when the user sets it to a non-empty value.
this allows us to easily use the cluster default load balancer class.
this is required to use metallb instead of kube-vip.
here's an usage example:
```bash
helm upgrade --install \
stack \
. \
--create-namespace \
--namespace tink-system \
--wait \
--values <(cat <<EOF
stack:
...
lbClass: ""
kubevip:
enabled: false
boots:
service:
class: ""
...
EOF
)
```
It was tested in a k3s cluster using metallb.
It does not impact existing users as there are no breaking changes.
I have:
=> only set the loadBalancerClass property when the user sets it to a non-empty value

tinkerbell/stack/templates/nginx.yaml
When creating the helm chart, analysing the output, I noticed a duplicate label selector (`app: stack`). I searched for usage of this selector but found none. I propose to delete this selector for this reason.
Because I the current label is confusing and irrelevant.
Fixes: Duplicate label
I have installed the helm chart on an empty cluster.
I have gained the helm chart manifest files using the `--dry-run` flag.
I have removed the key and value from in the tink-stack load balancer service.
I have applied the changes using kustomize combining al the manifest files gained form the helm dry-run.
I have verified that the application is still working.
None
=> Removed unused and possibly duplicate label selector

tinkerbell/stack/README.md, tinkerbell/stack/templates/nginx.yaml, tinkerbell/stack/values.yaml
Simplify the nginx commands and verify the checksums after download.
Simplifies the code.
Tested by launching the k8s stack in https://github.com/rgl/tinkerbell-k8s-vagrant
None.
I have:
=> Simplify the nginx commands and verify the checksums after download

tinkerbell/stack/templates/nginx.yaml
This fixes any issues where the `nameserver` line is not the second line in the `resolv.conf` file. 
Fixes: #56 
I have:
=> Make awk command more resilient:

tinkerbell/stack/Chart.yaml, tinkerbell/stack/templates/nginx.yaml, tinkerbell/stack/values.yaml
Hook now provides a checksum file. Use it to verify downloads of Hook.
Fixes: #
Manually tested.
I have:
=> Use checksum from Hook release:

tinkerbell/stack/templates/nginx.yaml
If multiple default routes exists, we should only use the first one.
Fixes: #
I have:
=> Update default route interface lookup:

tinkerbell/rufio/Chart.yaml, tinkerbell/rufio/crds/bmc.tinkerbell.org_jobs.yaml, tinkerbell/rufio/crds/bmc.tinkerbell.org_machines.yaml, tinkerbell/rufio/crds/bmc.tinkerbell.org_tasks.yaml, tinkerbell/stack/Chart.lock, tinkerbell/stack/Chart.yaml
The CRD for Rufio were not updated to match the Rufio version. Even though the stack chart itself didn't change, we only create an OCI image for the stack chart. So this update to the Rufio chart necessitates a stack chart version bump.
Fixes: #
I have:
=> Update Rufio CRDs:

tinkerbell/stack/values.yaml
Change to https://github.com/jacobweinstock/dhcrelay/pkgs/container/dhcprelay (from https://github.com/jacobweinstock/dhcrelay/pkgs/container/dhcrelay)
This enables deploying the stack chart on arm64.
=> stack: relay: use multiarch dhcp-relay image ghcr.io/jacobweinstock/dhcprelay

tinkerbell/stack/README.md, tinkerbell/stack/templates/nginx.yaml, tinkerbell/stack/values.yaml
Introduce presentGIAddr to control the handling of incoming DHCPv4 packets which already contain relay agent options.
When there are more relay agents - having append would result in multiple `Agent-Information`.
=> stack: add dhcrelay giaddr control behaviour

tinkerbell/stack/templates/nginx-configmap.yaml, tinkerbell/stack/templates/nginx.yaml, tinkerbell/stack/values.yaml
Use a value instead of `cluster.local` hardcoded in a few places.
Some clusters might not have cluster.local domain, although it is the default.
=> charts: stack: introduce stack.clusterDomain to replace hardcoded `cluster.local` values

tinkerbell/stack/templates/nginx.yaml, tinkerbell/stack/values.yaml
Use 127.1.1.1/32 for the DHCP broadcast interface instead of the load balancer IP. Using the load balancer IP can cause instability with that address and routing to Kubernetes services. And as we only send broadcast packets from this interface the IP is needed but doesn't need to be in the subnet.
Make the DHCP broadcast interface name static. The dynamic number that was added to the name causes restarts on every Helm install/upgrade and is not needed.
Add ipvlan support for the DHCP broadcast interface. This allows deployment where creating and broadcasting a new Mac address can be prohibited or rejected. VMware for example by default sets forged transmits to reject and causes packets for the macvlan interface to be dropped.
Allow enabling/disabling of listening for DHCP broadcast …
=> Update DHCP broadcast interface handling:

tinkerbell/stack/templates/nginx.yaml
There is an issue with ipvlan interfaces not receiving packets after creation. This works around this issue to get packets flowing. This should be investigated deeper to understand why this is happening.
Fixes: #
I have:
=> Workaround for ipvlan interfaces:

tinkerbell/stack/templates/hook.yaml
Releases of HookOS > 0.8.1 provide more binaries. We only need the hook_aarch64 and hook_x86_64 binaries so we filter out the rest.
Fixes: #
I have:
=> Handle shasum checking for HookOS > 0.8.1:

tinkerbell/rufio/crds/bmc.tinkerbell.org_machines.yaml, tinkerbell/tink/crds/hardware-crd.yaml, tinkerbell/tink/crds/template-crd.yaml
Adds `clusterctl` and `clusterctl/move` labels to rufio bmc machine CRDs and tink hardware and template CRDs.
This allows the machine CRs to be moved during a `clusterctl move` command. 
Tested with EKS-Anywhere to confirm that crds are not left behind when performing `clusterctl move`
=> Add clusterctl labels to crds

tinkerbell/stack/templates/nginx.yaml, tinkerbell/stack/values.yaml
When `interfaceMode: ipvlan` is not set the existing container image might not be desireable.
Fixes: #
I have:
=> Make dhcp-relay init container configurable:

tinkerbell/stack/templates/nginx.yaml
Fixes: https://github.com/tinkerbell/charts/issues/98
Tested locally with EKS-Anywhere and verified that the tink-stack relay container does not start when `enabled: false`
This fixes a bug where `stack.relay.enabled: false` gets ignored
=> Allow tink-stack relay to be disbaled

tinkerbell/hegel/Chart.yaml, tinkerbell/hegel/templates/deployment.yaml, tinkerbell/hegel/values.yaml, tinkerbell/rufio/Chart.yaml, tinkerbell/rufio/templates/deployment.yaml, tinkerbell/rufio/values.yaml, tinkerbell/smee/Chart.yaml, tinkerbell/smee/templates/deployment.yaml, tinkerbell/smee/values.yaml, tinkerbell/stack/Chart.lock, tinkerbell/stack/Chart.yaml, tinkerbell/stack/values.yaml, tinkerbell/tink/Chart.yaml, tinkerbell/tink/templates/tink-controller/deployment.yaml, tinkerbell/tink/templates/tink-server/deployment.yaml, tinkerbell/tink/values.yaml
We have a larger kubernetes cluster running and need to be able to control which node the tinkerbell pods run on. The easiest way for us is to control the pods via a node label and nodeSelector
We have installed a 3 node RKE2 cluster and the nodes on which the Tinkerbell pods are to run with
`node-role.kubernetes.io/tinkerbell: 'true'`.
With the helm value
```
nodeSelector:
node-role.kubernetes.io/tinkerbell: 'true'
```
We then deployed the Tinkerbell stack and checked which nodes the pods were running on.
=> Nodeselector

tinkerbell/rufio/templates/deployment.yaml, tinkerbell/rufio/values.yaml, tinkerbell/smee/templates/_ports.tpl, tinkerbell/stack/templates/kubevip.yaml, tinkerbell/stack/values.yaml
This PR adds the following:
- Templates out the args for the rufio deployment so that users can provide other rufio flags if desired.
- Updates "urlJoiner" to not add a colon to the url if no port is provided
- Allows kubevip `prometheus_server` to be set to override the default address
These changes allow the tinkerbell chart to be more customizable for various use cases
Tested manually with EKS-Anywhere
I have:
=> Tinkerbell chart improvements

tinkerbell/stack/templates/nginx-configmap.yaml, tinkerbell/stack/templates/nginx.yaml
This removes issues when both Smee and nginx want to listen on the same ports.
Fixes: #
I have:
=> Remove nginx Smee services when Smee's in hostNetwork mode:

tinkerbell/hegel/Chart.yaml, tinkerbell/hegel/templates/_scheduling.tpl, tinkerbell/hegel/templates/deployment.yaml, tinkerbell/hegel/values.yaml, tinkerbell/rufio/Chart.yaml, tinkerbell/rufio/templates/_scheduling.tpl, tinkerbell/rufio/templates/deployment.yaml, tinkerbell/rufio/values.yaml, tinkerbell/smee/Chart.yaml, tinkerbell/smee/templates/_scheduling.tpl, tinkerbell/smee/templates/deployment.yaml, tinkerbell/smee/values.yaml, tinkerbell/stack/Chart.lock, tinkerbell/stack/Chart.yaml, tinkerbell/stack/templates/_scheduling.tpl, tinkerbell/stack/templates/kubevip.yaml, tinkerbell/stack/templates/nginx.yaml, tinkerbell/stack/values.yaml, tinkerbell/tink/Chart.yaml, tinkerbell/tink/templates/tink-controller/_scheduling.tpl, tinkerbell/tink/templates/tink-controller/deployment.yaml, tinkerbell/tink/templates/tink-server/_scheduling.tpl, tinkerbell/tink/templates/tink-server/deployment.yaml, tinkerbell/tink/values.yaml
This PR adds tolerations to all the deployments
These tolerations are needed to create single node clusters successfully.
Manually tested with EKS-Anywhere
=> Add control plane tolerations to deployments

tinkerbell/rufio/templates/cluster-role.yaml
Reverts tinkerbell/charts#102
Rufio uses controller-runtime. Controller-runtime needs list permissions for its caching mechanism.
_"// Cache is the cache.Options that will be used to create the default Cache.
// By default, the cache will watch and list requested objects in all namespaces."_ -  https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#Options
https://github.com/kubernetes-sigs/controller-runtime/issues/1220
=> Revert "Remove list permission on secrets for Rufio:"

tinkerbell/rufio/templates/deployment.yaml, tinkerbell/rufio/values.yaml
We run an RKE2 IPv6 only cluster.
Three network cards are configured on the nodes (two with IPv6 and one with IPv4, which is only responsible for BMC traffic)
As CNI we use cilium with a very simple config (nothing is specially set here)
we have also not set any special egress or ingress rules.
If we now run rufio in the cluster network, we get no traffic to the BMC. In the logs there is a "not authenticated" error and using tcpdump I don't see any traffic.
If we now run rufio in the host network, I see traffic in the tcpdump and the node can also be restarted using rufio via the BMC.
We therefore need the option to set the host network here.
I already had an conversation with @jacobweinstock about this via Slack
=> add hostNetwork to rufio

tinkerbell/stack/templates/init_configmap.yaml, tinkerbell/stack/templates/nginx.yaml, tinkerbell/stack/values.yaml
Things like left over interfaces shouldn't cause crashloops anymore.
> [!NOTE]
> If flipping between `stack.relay.interfaceMode=macvlan` and `stack.relay.interfaceMode=ipvlan`, the deployment strategy must be set to `Recreate`. This is because of a limitation in being able to create both macvlan and ipvlan interfaces with the same parent at the same time on the same node.
Fixes: #110 
I have:
=> Make relay init container script more resilient:

tinkerbell/stack/templates/nginx-configmap.yaml, tinkerbell/stack/templates/nginx.yaml
When Smee is disabled we weren't removing references to ports and nginx conf lines.
Fixes: #
I have:
=> Gate changes in Stack chart for Smee:

tinkerbell/stack/values.yaml
The latest tag changes with every push to main in the Hook repo. This has caused issue with the checksum validation.
Fixes: #
I have:
=> Use tagged version of HookOS:

tinkerbell/stack/README.md
Updating docs to provide correct paths
Fixes: #121 
I tested by adding 
```yaml
stack: 
kubevip:
enabled: false
```
to my helm overrides and confirmed it disabled the kubevip deployment.
If they were following the docs, no configurations were actually set.
I have:
=> fixing kubevip documented value paths

tinkerbell/stack/values.yaml
This should help the stack deployment work natively for more environments with DHCP relays in play.
Fixes: #
I have:
=> Make `presentGiaddrAction: forward`, the default:

tinkerbell/hegel/templates/deployment.yaml, tinkerbell/hegel/templates/role.yaml, tinkerbell/hegel/templates/rolebinding.yaml, tinkerbell/hegel/values.schema.json, tinkerbell/rufio/templates/deployment.yaml, tinkerbell/rufio/templates/role-binding.yaml, tinkerbell/rufio/templates/role.yaml, tinkerbell/rufio/values.schema.json, tinkerbell/smee/templates/deployment.yaml, tinkerbell/smee/templates/role-binding.yaml, tinkerbell/smee/templates/role.yaml, tinkerbell/smee/values.schema.json, tinkerbell/smee/values.yaml, tinkerbell/stack/README.md, tinkerbell/stack/templates/nginx.yaml, tinkerbell/stack/values.schema.json, tinkerbell/stack/values.yaml, tinkerbell/tink/templates/tink-controller/deployment.yaml, tinkerbell/tink/templates/tink-controller/role-binding.yaml, tinkerbell/tink/templates/tink-controller/role.yaml, tinkerbell/tink/templates/tink-server/deployment.yaml, tinkerbell/tink/templates/tink-server/role-binding.yaml, tinkerbell/tink/templates/tink-server/role.yaml, tinkerbell/tink/values.schema.json
This allows all rbac to be toggled between Role and ClusterRole. It also simplifies the trustedProxies for Hegel and Smee and the loadBalancerIP/publicIP shared between the stack and Smee. The Helm install experience is improved, in my opinion.
I also removed all the required fields in the values.schema.json so that flexibility of configuration is not limited.
Fixes: #
I have:
=> Improve rbac setting by using Helm globals:

tinkerbell/smee/templates/deployment.yaml, tinkerbell/smee/values.yaml
- this fits in with
-  https://github.com/tinkerbell/smee/pull/479
-  https://github.com/tinkerbell/tink/pull/960
- https://github.com/tinkerbell/hook/pull/234
Signed-off-by: Ricardo Pardini <ricardo@pardini.net>
=> smee: add http.tinkServer.insecureTLS controlling `-tink-server-insecure-tls`

tinkerbell/stack/templates/nginx.yaml
If dhrelay is disabled, smee needs to be exposed directly via loadbalancer instead.
Currently, if dhrelay is disabled, smee can't be accessed.
=> stack: directly expose smee when relay is disabled

tinkerbell/smee/templates/deployment.yaml, tinkerbell/smee/values.yaml
Adds generic `tolerations` and `affinity` fields to the values
This way, users have more control over where the smee pod is running.
We have a setup where a specific node is added to the management-cluster, which is in the same L2 network as the machines that are being provisioned (as is required by dhcp).
(Before this we had a separate vm running in the target network, running smee with extra configurations so that it can grab the required configurations from the management cluster externally, but that setup is way more complicated, having to put serviceaccount tokens in there and everything)
With this new chart setup, added specific tolerations and affinity that target a taint/label on the 'special' node which is in the target network.  After that, provisioned some machines which worked …
=> Enable generic settting of tolerations and affinity for smee deployment

tinkerbell/stack/templates/nginx.yaml
the tink-stack pod crashes on an ipv6 only cluster because the container can not handle IPv6 addresses
```
:~# kubectl logs -n tink-system tink-stack-6bbc556dd-znd6j
Defaulted container "tink-stack" out of: tink-stack, dhcp-relay
++ awk '/nameserver/ {print $2}' /etc/resolv.conf
+ POD_NAMESERVER=fd05:0000:0000::a
+ envsubst '$POD_NAMESERVER'
+ exec nginx -g 'daemon off;'
2024/06/03 16:23:37 [emerg] 3210953#3210953: invalid port in resolver "fd05:0000:0000::a" in /etc/nginx/nginx.conf:13
nginx: [emerg] invalid port in resolver "fd05:0000:0000::a" in /etc/nginx/nginx.conf:13
```
We use an IPv6 only RKE2 Cluster and we need to start this container correctly.
Fixes: #99
I tested the fix in our RKE2 IPv6 only cluster and it works. But i don't have an IPv4 environment for testing
=> fix container for ipv6

tinkerbell/smee/templates/deployment.yaml
Due to a special network configuration, we have to run smee in the host network so that dhcp requests can  be received and be responded to the destination host.
It looks like the IP of an undesired interface is being used by default.
eno8303 = wrong
lcm@infra = correct
```
2: eno8303: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000                                                                           
link/ether c4:cb:e1:a6:9e:e0 brd ff:ff:ff:ff:ff:ff                                                                                                                     
altname enp4s0f0                                                                                                                                                       
inet …
```
=> remove hostnetwork check for addr configuration of the smee services

tinkerbell/tink/templates/tink-controller/deployment.yaml
Without patch passing args to tink controller works not correctly.
```Helm
set_list {
name  = "tink.controller.args"
value = ["--log-level=1"]  # debug
}
```
Resulted pod:
```yaml
args:
- '--namespace=tink-system - --log-level=1'
```
Tink Controller Chart pass args not correctly.
For instance, for passing `--log-level`
I didn't test it, but in another module use the same construction and works correctly: https://github.com/tinkerbell/charts/blob/29de47ae2be2581247573f03b613ac3214c38be3/tinkerbell/tink/templates/tink-server/deployment.yaml#L42
Tink Controller Chart pass args not correctly.
I have:
=> Fix controller deployment args

tinkerbell/rufio/Chart.yaml, tinkerbell/rufio/crds/bmc.tinkerbell.org_machines.yaml, tinkerbell/rufio/crds/bmc.tinkerbell.org_tasks.yaml, tinkerbell/rufio/values.yaml, tinkerbell/stack/Chart.lock, tinkerbell/stack/Chart.yaml
This include an API change to the {machine,task}.bmc.tinkerbell.org CRDs.
Fixes: #
I have:
=> Update Rufio version and CRDs:

tinkerbell/smee/Chart.yaml, tinkerbell/smee/templates/service.yaml, tinkerbell/stack/Chart.lock, tinkerbell/stack/Chart.yaml, tinkerbell/stack/templates/hook.yaml, tinkerbell/stack/templates/nginx-configmap.yaml, tinkerbell/stack/templates/nginx.yaml, tinkerbell/stack/templates/nginx_pvc.yaml, tinkerbell/stack/values.yaml
New HookOS download script enables downloading tar.gz and .iso files. It also allows for downloading based on architecture, kernel version, or extention.
Fixes: #
I have:
=> Update HookOS downloading:

tinkerbell/hegel/Chart.yaml, tinkerbell/hegel/values.yaml, tinkerbell/smee/Chart.yaml, tinkerbell/smee/templates/deployment.yaml, tinkerbell/smee/values.yaml, tinkerbell/stack/Chart.lock, tinkerbell/stack/Chart.yaml, tinkerbell/stack/values.yaml
Also, updates kubevip and nginx container image versions.
Fixes: #
I have:
=> Update Smee, Hegel, and Rufio versions:

tinkerbell/smee/Chart.yaml, tinkerbell/smee/templates/deployment.yaml, tinkerbell/stack/Chart.lock, tinkerbell/stack/Chart.yaml
This allows an unset value for an env variable to invoke Smee's automatic IP detection to trigger. With CLI flags this automatic IP detection doesnt work.
Fixes: #
I have:
=> Use env vars in Smee instead of CLI flags:

tinkerbell/smee/Chart.yaml, tinkerbell/smee/values.yaml, tinkerbell/stack/Chart.lock, tinkerbell/stack/Chart.yaml
There were inconsistency in the formatting of the Smee chart. The trustedProxies was not all the way left when it should have been. It doesn't appear to affect it being set properly but needed fixed regardless.
Fixes: #
I have:
=> Yaml format Smee chart, align trustedProxies properly:

tinkerbell/rufio/Chart.yaml, tinkerbell/rufio/crds/bmc.tinkerbell.org_machines.yaml, tinkerbell/stack/Chart.lock, tinkerbell/stack/Chart.yaml, tinkerbell/tink/Chart.yaml, tinkerbell/tink/crds/hardware-crd.yaml
CAPI requires these labels exist on the CRDs when doing a `clusterctl move`.
Fixes: #
I have:
=> Add CAPI labels to machines.bmc and hardware CRDs:
